# version: '3.3'
# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: testuser
#       MONGO_INITDB_ROOT_PASSWORD: testpassword
#       # AUTH: admin
#       MONGO_INITDB_DATABASE: admin
#     ports:
#       - '27018:27017'
#     volumes:
#       - 'my_mongodb_data:/data/db'

#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express
#     restart: always 
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
#       ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
#       ME_CONFIG_MONGODB_SERVER: mongodb
#       ME_CONFIG_MONGODB_AUTH_DATABASE: admin  
#     ports:
#       - '8081:8081'
#     depends_on:
#       - mongodb

# volumes:
#   my_mongodb_data:
#     driver: local
    

version: '3.0'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
      MONGO_INITDB_DATABASE: admin
    ports:
      - '27018:27017'
    volumes:
      - 'my_mongodb_data:/data/db'

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: your_admin_username
      ME_CONFIG_BASICAUTH_PASSWORD: your_admin_password
    ports:
      - '8081:8081'
    depends_on:
      - mongodb

volumes:
  my_mongodb_data:
    driver: local
